spring:
  application:
    name: user-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
server:
  port: 0